require: rubocop-rails

Documentation:
  Enabled: false

AllCops:
 Exclude:
  - db/**/*
  - bin/bundle
  
Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - spec/requests/*.rb

Style/StringConcatenation:
  Exclude:
    - config/initializers/rswag_api.rb

Metrics/AbcSize:
  Exclude:
    - app/controllers/users/omniauth_callbacks_controller.rb
    - app/models/user.rb
    - app/controllers/sign_up_controller.rb

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/omniauth_callbacks_controller.rb

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/Rails/InverseOf:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
