---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/{locale}/users/{id}":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    minimum: 1
                  name:
                    type: string
                  description:
                    type: string
                  email:
                    type: string
                  avatar_url:
                    type: string
                required:
                - id
                - name
                - description
                - email
                - avatar_url
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
