---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
servers:
- url: http://{herokuapp}
  variables:
    herokuapp:
      default: lessoner.herokuapp.com/
- url: http://{localHost1}
  variables:
    localHost1:
      default: localhost:3000/
- url: http://{localHost2}
  variables:
    localHost2:
      default: 127.0.0.1:3000/
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    category:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - active
          - archived
      required:
      - id
      - name
      - description
      - status
    create_category:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - active
          - archived
      required:
      - name
      - description
    update_category:
      type: object
      minProperties: 1
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - active
          - archived
    lesson:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
        description:
          type: string
      required:
      - id
      - title
      - description
    create_lesson:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        video_link:
          type: string
        status:
          type: string
        author_id:
          type: integer
          minimum: 1
      required:
      - title
      - description
      - status
      - video_link
      - author_id
    lesson_extended:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
        description:
          type: string
        video_link:
          type: string
        status:
          type: string
        author_id:
          type: integer
          minimum: 1
      required:
      - title
      - description
      - status
      - video_link
      - author_id
    update_lesson:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
        description:
          type: string
        video_link:
          type: string
        status:
          type: string
        author_id:
          type: integer
          minimum: 1
      required:
      - title
      - description
      - status
      - video_link
      - author_id
