---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/{locale}/categories":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    get:
      summary: list categories
      tags:
      - Categories
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/category"
    post:
      summary: create category
      tags:
      - Categories
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/category"
        '422':
          description: invalid request
          content:
            application/json:
              examples:
                example_blank_name:
                  value:
                    errors:
                      name:
                      - can't be blank
                example_blank_description:
                  value:
                    errors:
                      description:
                      - can't be blank
              schema:
                "$ref": "#/components/schemas/errors_object"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/create_category"
  "/{locale}/categories/{id}":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      tags:
      - Categories
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/category"
    put:
      summary: update category
      tags:
      - Categories
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/category"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/update_category"
  "/{locale}/lessons":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    get:
      summary: list lessons
      tags:
      - Lessons
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_key:
                  value:
                    title: Ruby on Rails
                    description: Introduce
                    id: '1'
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/lesson"
    post:
      summary: create lesson
      tags:
      - Lessons
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_key:
                  value:
                    title: Ruby on Rails
                    description: Introduce
                    video_link: link
                    status: status
                    author_id: 1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/create_lesson"
  "/{locale}/lessons/{id}":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show lesson
      tags:
      - Lessons
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_key:
                  value:
                    title: Ruby on Rails
                    description: Introduce
                    vvideo_link: link
                    status: status
                    author_id: 1
    put:
      summary: update lesson
      tags:
      - Lessons
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_key:
                  value:
                    title: Ruby on Rails
                    description: Introduce
                    vvideo_link: link
                    status: status
                    author_id: 1
                    id: 1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/update_lesson"
    delete:
      summary: delete lesson
      tags:
      - Lessons
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_key:
                  value:
                    id: 1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/update_lesson"
  "/sign_up":
    post:
      summary: create sign_up
      tags:
      - Sign_up
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    minimum: 1
                  name:
                    type: string
                  phone:
                    type: string
                  gender:
                    type: string
                    enum:
                    - male
                    - female
                    - other
                  email:
                    type: string
                  birthday:
                    type: string
                required:
                - id
                - name
                - gender
                - email
        '400':
          description: bad request
          content:
            application/json:
              examples:
                example_already_exists:
                  value:
                    errors:
                    - Email has already been taken
                    - Name has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                gender:
                  type: string
                  enum:
                  - male
                  - female
                  - other
                email:
                  type: string
                birthday:
                  type: string
                  format: date
                password:
                  type: string
              required:
              - name
              - gender
              - email
              - password
  "/{locale}/users/{id}":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    minimum: 1
                  name:
                    type: string
                  description:
                    type: string
                  email:
                    type: string
                  avatar_url:
                    type: string
                required:
                - id
                - name
                - description
                - email
                - avatar_url
  "/{locale}/check_username?name={username}":
    parameters:
      - name: locale
        in: path
        description: locale
        required: true
        schema:
          type: string
      - name: username
        in: path
        description: username
        required: true
        schema:
          type: string
    get:
      summary: check username
      tags:
        - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  username_exists:
                    type: boolean
                required:
                  - username_exists
  "/{locale}/check_email?email={email}":
    parameters:
      - name: locale
        in: path
        description: locale
        required: true
        schema:
          type: string
      - name: email
        in: path
        description: email
        required: true
        schema:
          type: string
    get:
      summary: check email
      tags:
        - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  email_exists:
                    type: boolean
                required:
                  - email_exists
servers:
- url: http://{herokuapp}
  variables:
    herokuapp:
      default: lessoner.herokuapp.com/
- url: http://{localHost1}
  variables:
    localHost1:
      default: localhost:3000/
- url: http://{localHost2}
  variables:
    localHost2:
      default: 127.0.0.1:3000/
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    category:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - active
          - archived
      required:
      - id
      - name
      - description
      - status
    create_category:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - active
          - archived
      required:
      - name
      - description
    update_category:
      type: object
      minProperties: 1
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - active
          - archived
    lesson:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
        description:
          type: string
      required:
      - id
      - title
      - description
    create_lesson:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        video_link:
          type: string
        status:
          type: string
        author_id:
          type: integer
          minimum: 1
      required:
      - title
      - description
      - status
      - video_link
      - author_id
    lesson_extended:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
        description:
          type: string
        video_link:
          type: string
        status:
          type: string
        author_id:
          type: integer
          minimum: 1
      required:
      - title
      - description
      - status
      - video_link
      - author_id
    update_lesson:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
        description:
          type: string
        video_link:
          type: string
        status:
          type: string
        author_id:
          type: integer
          minimum: 1
      required:
      - title
      - description
      - status
      - video_link
      - author_id
