name: Verify

on:
  - push
  - pull_request

jobs:
  test:
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.115.3
        with:
          ruby-version: 3.1.2

      - name: Install Dependencies
        run: |
          sudo apt-get install -yqq libpq-dev
          sudo apt-get install -y libvips
          gem install bundler

      - name: Install Gems
        run: |
          bundle install
#
#      - name: Run Tests
#        run: |
#          bundle exec rspec spec/*
#
#      - name: Test
#        run: bundle exec rspec -f j -o tmp/rspec_results.json -f p
#
#      - name: RSpec Report
#        uses: SonicGarden/rspec-report-action@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          json-path: tmp/rspec_results.json
#        if: always()

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.115.3
        with:
          ruby-version: 3.1.2

      - name: Install Brakeman
        run: |
          gem install brakeman

      - name: Run Brakeman
        run: |
          brakeman -f json > tmp/brakeman.json || exit 0

      - name: Brakeman Report
        uses: devmasx/brakeman-linter-action@v1.0.0
        env:
          REPORT_PATH: tmp/brakeman.json
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: rubocop
        uses: reviewdog/action-rubocop@v2.3.1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile
          github_token: ${{ secrets.github_token }}
